import type { PatternDefinition } from "../../types";

export const bookingPattern: PatternDefinition = {
  id: "booking",
  name: "Booking / Scheduling",
  description: "Service booking platform with providers, availability, appointments, and payments.",
  keywords: ["booking", "appointment", "schedule", "calendar", "slot", "reservation", "availability", "service", "provider"],
  standardEntities: [
    {
      name: "Service",
      description: "A bookable service offered by providers.",
      fields: [
        { name: "id", type: "string", required: true, unique: true },
        { name: "name", type: "string", required: true },
        { name: "slug", type: "string", required: true, unique: true },
        { name: "description", type: "string", required: true },
        { name: "duration", type: "number", required: true, description: "Duration in minutes" },
        { name: "price", type: "number", required: true },
        { name: "categoryId", type: "ref", required: false, refEntity: "ServiceCategory" },
        { name: "bufferTime", type: "number", required: false, defaultValue: "0" },
        { name: "maxAdvanceBooking", type: "number", required: false, description: "Max days in advance" },
        { name: "isActive", type: "boolean", required: true, defaultValue: "true" },
      ],
      relationships: [{ type: "has_many", targetEntity: "Booking" }],
      businessRules: ["Buffer time between consecutive bookings", "Max advance booking limit"],
    },
    {
      name: "Provider",
      description: "Service provider with availability.",
      fields: [
        { name: "id", type: "string", required: true, unique: true },
        { name: "userId", type: "ref", required: true, refEntity: "User" },
        { name: "name", type: "string", required: true },
        { name: "bio", type: "string", required: false },
        { name: "avatar", type: "string", required: false },
        { name: "services", type: "array", required: true },
        { name: "availability", type: "object", required: true, description: "Weekly schedule" },
        { name: "timezone", type: "string", required: true },
      ],
      relationships: [
        { type: "belongs_to", targetEntity: "User" },
        { type: "has_many", targetEntity: "Booking" },
        { type: "has_many", targetEntity: "AvailabilityOverride" },
      ],
      businessRules: ["Availability defined as weekly recurring schedule", "Overrides for holidays/time-off"],
    },
    {
      name: "Booking",
      description: "A scheduled appointment.",
      fields: [
        { name: "id", type: "string", required: true, unique: true },
        { name: "serviceId", type: "ref", required: true, refEntity: "Service" },
        { name: "providerId", type: "ref", required: true, refEntity: "Provider" },
        { name: "customerId", type: "ref", required: true, refEntity: "User" },
        { name: "startTime", type: "datetime", required: true },
        { name: "endTime", type: "datetime", required: true },
        { name: "status", type: "enum", required: true, enumValues: ["pending", "confirmed", "cancelled", "completed", "no_show"] },
        { name: "notes", type: "string", required: false },
        { name: "paymentId", type: "string", required: false },
        { name: "cancellationReason", type: "string", required: false },
      ],
      relationships: [
        { type: "belongs_to", targetEntity: "Service" },
        { type: "belongs_to", targetEntity: "Provider" },
        { type: "belongs_to", targetEntity: "User" },
      ],
      businessRules: [
        "No double-booking for same provider and time slot",
        "Cancellation allowed up to 24h before appointment",
        "Auto-confirm or require provider confirmation based on settings",
        "Reminder emails 24h and 1h before",
      ],
    },
    {
      name: "AvailabilityOverride",
      description: "Override for a provider's regular schedule (holiday, time-off).",
      fields: [
        { name: "id", type: "string", required: true, unique: true },
        { name: "providerId", type: "ref", required: true, refEntity: "Provider" },
        { name: "date", type: "date", required: true },
        { name: "isBlocked", type: "boolean", required: true },
        { name: "customSlots", type: "array", required: false },
        { name: "reason", type: "string", required: false },
      ],
      relationships: [{ type: "belongs_to", targetEntity: "Provider" }],
      businessRules: [],
    },
    {
      name: "User",
      description: "Customer or provider user.",
      fields: [
        { name: "id", type: "string", required: true, unique: true },
        { name: "email", type: "string", required: true, unique: true },
        { name: "name", type: "string", required: true },
        { name: "passwordHash", type: "string", required: true },
        { name: "role", type: "enum", required: true, enumValues: ["customer", "provider", "admin"] },
        { name: "phone", type: "string", required: false },
        { name: "timezone", type: "string", required: false },
      ],
      relationships: [{ type: "has_many", targetEntity: "Booking" }],
      businessRules: [],
    },
    {
      name: "ServiceCategory",
      description: "Category for grouping services.",
      fields: [
        { name: "id", type: "string", required: true, unique: true },
        { name: "name", type: "string", required: true },
        { name: "slug", type: "string", required: true, unique: true },
      ],
      relationships: [{ type: "has_many", targetEntity: "Service" }],
      businessRules: [],
    },
  ],
  standardScreens: [
    { name: "Service Browse", route: "/", description: "Browse services and providers", layout: "public", accessRoles: ["*"], entities: ["Service", "Provider", "ServiceCategory"] },
    { name: "Booking Flow", route: "/book/[serviceSlug]", description: "Select provider, date, time slot, confirm", layout: "public", accessRoles: ["*"], entities: ["Service", "Provider", "Booking"] },
    { name: "My Bookings", route: "/bookings", description: "Customer's upcoming and past bookings", layout: "dashboard", accessRoles: ["customer"], entities: ["Booking"] },
    { name: "Provider Calendar", route: "/provider/calendar", description: "Provider's schedule and bookings", layout: "dashboard", accessRoles: ["provider"], entities: ["Booking", "AvailabilityOverride"] },
    { name: "Provider Availability", route: "/provider/availability", description: "Set weekly schedule and overrides", layout: "dashboard", accessRoles: ["provider"], entities: ["Provider", "AvailabilityOverride"] },
    { name: "Admin Dashboard", route: "/admin", description: "All bookings, providers, services", layout: "admin", accessRoles: ["admin"], entities: ["Booking", "Service", "Provider"] },
  ],
  standardApiEndpoints: [
    { method: "GET", path: "/api/services", description: "List services", entity: "Service", authRequired: false },
    { method: "GET", path: "/api/providers/:id/slots", description: "Get available slots", entity: "Provider", authRequired: false },
    { method: "POST", path: "/api/bookings", description: "Create booking", entity: "Booking", authRequired: true },
    { method: "PATCH", path: "/api/bookings/:id/cancel", description: "Cancel booking", entity: "Booking", authRequired: true },
    { method: "GET", path: "/api/bookings", description: "List my bookings", entity: "Booking", authRequired: true },
    { method: "PUT", path: "/api/providers/:id/availability", description: "Update availability", entity: "Provider", authRequired: true, roles: ["provider"] },
    { method: "POST", path: "/api/providers/:id/overrides", description: "Add availability override", entity: "AvailabilityOverride", authRequired: true, roles: ["provider"] },
  ],
  standardRoles: [
    { name: "customer", description: "Can browse and book services", permissions: ["read:services", "manage:own-bookings"] },
    { name: "provider", description: "Manages own schedule and bookings", permissions: ["manage:own-availability", "manage:own-bookings", "read:own-customers"] },
    { name: "admin", description: "Full platform management", permissions: ["manage:all"] },
  ],
  standardBusinessRules: [
    { entity: "Booking", rule: "No double-booking validation on creation", type: "constraint" },
    { entity: "Booking", rule: "24h cancellation policy", type: "constraint" },
    { entity: "Booking", rule: "Auto-reminders at 24h and 1h before", type: "workflow" },
    { entity: "Provider", rule: "Availability computed by merging weekly schedule and overrides", type: "computation" },
  ],
  deduplicationRules: [
    "Customer and provider booking views share BookingCard component with role-based actions",
    "Calendar component reused for provider schedule and admin overview",
    "Service browse and booking flow share ServiceCard component",
  ],
  antiPatterns: [
    "Storing availability as individual time slots instead of rules",
    "Client-side slot availability calculation without server validation",
    "Timezone handling only on frontend",
  ],
};
