import type { PatternDefinition } from "../../types";

export const cmsPattern: PatternDefinition = {
  id: "cms",
  name: "CMS / Blog",
  description: "Content management system with posts, categories, tags, media library, and editorial workflow.",
  keywords: ["cms", "blog", "post", "article", "content", "editor", "publish", "draft", "category", "tag", "media", "author"],
  standardEntities: [
    {
      name: "Post",
      description: "Content article or blog post.",
      fields: [
        { name: "id", type: "string", required: true, unique: true },
        { name: "title", type: "string", required: true },
        { name: "slug", type: "string", required: true, unique: true },
        { name: "content", type: "string", required: true },
        { name: "excerpt", type: "string", required: false },
        { name: "coverImage", type: "string", required: false },
        { name: "authorId", type: "ref", required: true, refEntity: "User" },
        { name: "categoryId", type: "ref", required: true, refEntity: "Category" },
        { name: "tags", type: "array", required: false },
        { name: "status", type: "enum", required: true, enumValues: ["draft", "review", "published", "archived"] },
        { name: "publishedAt", type: "datetime", required: false },
        { name: "seoTitle", type: "string", required: false },
        { name: "seoDescription", type: "string", required: false },
        { name: "readingTime", type: "number", required: false },
      ],
      relationships: [
        { type: "belongs_to", targetEntity: "User" },
        { type: "belongs_to", targetEntity: "Category" },
        { type: "has_many", targetEntity: "Comment" },
        { type: "many_to_many", targetEntity: "Tag" },
      ],
      businessRules: [
        "Draft→Review→Published→Archived workflow",
        "Slug auto-generated from title",
        "Reading time auto-calculated from content word count",
        "Published date set on first publish",
      ],
    },
    {
      name: "Category",
      description: "Content category.",
      fields: [
        { name: "id", type: "string", required: true, unique: true },
        { name: "name", type: "string", required: true },
        { name: "slug", type: "string", required: true, unique: true },
        { name: "description", type: "string", required: false },
      ],
      relationships: [{ type: "has_many", targetEntity: "Post" }],
      businessRules: [],
    },
    {
      name: "Tag",
      description: "Content tag for cross-cutting classification.",
      fields: [
        { name: "id", type: "string", required: true, unique: true },
        { name: "name", type: "string", required: true },
        { name: "slug", type: "string", required: true, unique: true },
      ],
      relationships: [{ type: "many_to_many", targetEntity: "Post" }],
      businessRules: [],
    },
    {
      name: "Comment",
      description: "Reader comment on a post.",
      fields: [
        { name: "id", type: "string", required: true, unique: true },
        { name: "postId", type: "ref", required: true, refEntity: "Post" },
        { name: "authorName", type: "string", required: true },
        { name: "authorEmail", type: "string", required: true },
        { name: "body", type: "string", required: true },
        { name: "status", type: "enum", required: true, enumValues: ["pending", "approved", "spam"] },
        { name: "parentId", type: "ref", required: false, refEntity: "Comment" },
      ],
      relationships: [{ type: "belongs_to", targetEntity: "Post" }],
      businessRules: ["Comments require moderation by default", "Nested replies up to 3 levels"],
    },
    {
      name: "Media",
      description: "Uploaded media file.",
      fields: [
        { name: "id", type: "string", required: true, unique: true },
        { name: "filename", type: "string", required: true },
        { name: "url", type: "string", required: true },
        { name: "mimeType", type: "string", required: true },
        { name: "size", type: "number", required: true },
        { name: "alt", type: "string", required: false },
        { name: "uploadedBy", type: "ref", required: true, refEntity: "User" },
      ],
      relationships: [{ type: "belongs_to", targetEntity: "User" }],
      businessRules: ["Max file size enforced per role", "Image auto-optimization on upload"],
    },
    {
      name: "User",
      description: "Content author or admin.",
      fields: [
        { name: "id", type: "string", required: true, unique: true },
        { name: "email", type: "string", required: true, unique: true },
        { name: "name", type: "string", required: true },
        { name: "passwordHash", type: "string", required: true },
        { name: "role", type: "enum", required: true, enumValues: ["admin", "editor", "author"] },
        { name: "bio", type: "string", required: false },
        { name: "avatar", type: "string", required: false },
      ],
      relationships: [{ type: "has_many", targetEntity: "Post" }, { type: "has_many", targetEntity: "Media" }],
      businessRules: [],
    },
  ],
  standardScreens: [
    { name: "Blog Home", route: "/", description: "Recent posts, featured, categories", layout: "public", accessRoles: ["*"], entities: ["Post", "Category"] },
    { name: "Post Page", route: "/[slug]", description: "Full post with comments", layout: "public", accessRoles: ["*"], entities: ["Post", "Comment"] },
    { name: "Category Page", route: "/category/[slug]", description: "Posts filtered by category", layout: "public", accessRoles: ["*"], entities: ["Post", "Category"] },
    { name: "Tag Page", route: "/tag/[slug]", description: "Posts filtered by tag", layout: "public", accessRoles: ["*"], entities: ["Post", "Tag"] },
    { name: "Post Editor", route: "/admin/posts/[id]/edit", description: "Rich text editor with preview", layout: "admin", accessRoles: ["admin", "editor", "author"], entities: ["Post", "Category", "Tag", "Media"] },
    { name: "Post List (Admin)", route: "/admin/posts", description: "All posts with status filters", layout: "admin", accessRoles: ["admin", "editor"], entities: ["Post"] },
    { name: "Media Library", route: "/admin/media", description: "Upload, browse, manage media", layout: "admin", accessRoles: ["admin", "editor", "author"], entities: ["Media"] },
    { name: "Comment Moderation", route: "/admin/comments", description: "Approve/reject/spam comments", layout: "admin", accessRoles: ["admin", "editor"], entities: ["Comment"] },
  ],
  standardApiEndpoints: [
    { method: "GET", path: "/api/posts", description: "List published posts", entity: "Post", authRequired: false },
    { method: "GET", path: "/api/posts/:slug", description: "Get post by slug", entity: "Post", authRequired: false },
    { method: "POST", path: "/api/admin/posts", description: "Create post", entity: "Post", authRequired: true, roles: ["admin", "editor", "author"] },
    { method: "PUT", path: "/api/admin/posts/:id", description: "Update post", entity: "Post", authRequired: true },
    { method: "PATCH", path: "/api/admin/posts/:id/status", description: "Change post status", entity: "Post", authRequired: true },
    { method: "GET", path: "/api/categories", description: "List categories", entity: "Category", authRequired: false },
    { method: "POST", path: "/api/posts/:id/comments", description: "Add comment", entity: "Comment", authRequired: false },
    { method: "PATCH", path: "/api/admin/comments/:id", description: "Moderate comment", entity: "Comment", authRequired: true, roles: ["admin", "editor"] },
    { method: "POST", path: "/api/admin/media", description: "Upload media", entity: "Media", authRequired: true },
    { method: "GET", path: "/api/admin/media", description: "List media", entity: "Media", authRequired: true },
  ],
  standardRoles: [
    { name: "admin", description: "Full CMS access", permissions: ["manage:all"] },
    { name: "editor", description: "Can edit and publish all posts, moderate comments", permissions: ["manage:posts", "manage:comments", "manage:media"] },
    { name: "author", description: "Can create and manage own posts", permissions: ["manage:own-posts", "manage:media"] },
  ],
  standardBusinessRules: [
    { entity: "Post", rule: "Authors can only edit their own drafts; editors can edit all", type: "constraint" },
    { entity: "Post", rule: "Publishing requires editor or admin approval", type: "workflow" },
    { entity: "Comment", rule: "All comments pending moderation unless commenter is a known user", type: "workflow" },
    { entity: "Media", rule: "Images auto-resized to max 2000px and optimized", type: "constraint" },
  ],
  deduplicationRules: [
    "Category and tag pages use the same PostList component with different filters",
    "Post editor is one component for both create and edit modes",
    "Admin post list and public post list share PostCard component",
  ],
  antiPatterns: [
    "Storing post content as HTML instead of structured format (MDX/JSON)",
    "Separate upload flows for post images vs media library",
    "SEO metadata duplicated between post model and page component",
  ],
};
