import type { PatternDefinition } from "../../types";

export const crmPattern: PatternDefinition = {
  id: "crm",
  name: "CRM",
  description: "Customer relationship management with contacts, companies, deals, pipelines, and activity tracking.",
  keywords: ["crm", "contact", "lead", "pipeline", "deal", "opportunity", "customer relationship", "sales", "funnel"],
  standardEntities: [
    {
      name: "Contact",
      description: "Individual person/lead in the CRM.",
      fields: [
        { name: "id", type: "string", required: true, unique: true },
        { name: "firstName", type: "string", required: true },
        { name: "lastName", type: "string", required: true },
        { name: "email", type: "string", required: true, unique: true },
        { name: "phone", type: "string", required: false },
        { name: "companyId", type: "ref", required: false, refEntity: "Company" },
        { name: "ownerId", type: "ref", required: true, refEntity: "User" },
        { name: "status", type: "enum", required: true, enumValues: ["lead", "qualified", "customer", "churned"] },
        { name: "source", type: "enum", required: false, enumValues: ["website", "referral", "cold_call", "event", "other"] },
        { name: "tags", type: "array", required: false },
        { name: "notes", type: "string", required: false },
      ],
      relationships: [
        { type: "belongs_to", targetEntity: "Company" },
        { type: "has_many", targetEntity: "Deal" },
        { type: "has_many", targetEntity: "Activity" },
      ],
      businessRules: ["Contact owner responsible for follow-up", "Status auto-updates based on deal progression"],
    },
    {
      name: "Company",
      description: "Business organization associated with contacts.",
      fields: [
        { name: "id", type: "string", required: true, unique: true },
        { name: "name", type: "string", required: true },
        { name: "domain", type: "string", required: false },
        { name: "industry", type: "string", required: false },
        { name: "size", type: "enum", required: false, enumValues: ["1-10", "11-50", "51-200", "201-500", "500+"] },
        { name: "annualRevenue", type: "number", required: false },
      ],
      relationships: [
        { type: "has_many", targetEntity: "Contact" },
        { type: "has_many", targetEntity: "Deal" },
      ],
      businessRules: [],
    },
    {
      name: "Deal",
      description: "Sales opportunity tracked through pipeline stages.",
      fields: [
        { name: "id", type: "string", required: true, unique: true },
        { name: "title", type: "string", required: true },
        { name: "contactId", type: "ref", required: true, refEntity: "Contact" },
        { name: "companyId", type: "ref", required: false, refEntity: "Company" },
        { name: "ownerId", type: "ref", required: true, refEntity: "User" },
        { name: "pipelineId", type: "ref", required: true, refEntity: "Pipeline" },
        { name: "stageId", type: "ref", required: true, refEntity: "PipelineStage" },
        { name: "value", type: "number", required: true },
        { name: "probability", type: "number", required: false },
        { name: "expectedCloseDate", type: "date", required: false },
        { name: "status", type: "enum", required: true, enumValues: ["open", "won", "lost"] },
        { name: "lostReason", type: "string", required: false },
      ],
      relationships: [
        { type: "belongs_to", targetEntity: "Contact" },
        { type: "belongs_to", targetEntity: "Pipeline" },
        { type: "has_many", targetEntity: "Activity" },
      ],
      businessRules: ["Probability auto-set from pipeline stage", "Lost reason required when marking as lost"],
    },
    {
      name: "Pipeline",
      description: "Sales pipeline with ordered stages.",
      fields: [
        { name: "id", type: "string", required: true, unique: true },
        { name: "name", type: "string", required: true },
        { name: "isDefault", type: "boolean", required: true, defaultValue: "false" },
      ],
      relationships: [{ type: "has_many", targetEntity: "PipelineStage" }, { type: "has_many", targetEntity: "Deal" }],
      businessRules: ["One default pipeline must exist"],
    },
    {
      name: "PipelineStage",
      description: "A stage within a pipeline.",
      fields: [
        { name: "id", type: "string", required: true, unique: true },
        { name: "pipelineId", type: "ref", required: true, refEntity: "Pipeline" },
        { name: "name", type: "string", required: true },
        { name: "probability", type: "number", required: true },
        { name: "sortOrder", type: "number", required: true },
      ],
      relationships: [{ type: "belongs_to", targetEntity: "Pipeline" }],
      businessRules: [],
    },
    {
      name: "Activity",
      description: "Logged interaction (call, email, meeting, note).",
      fields: [
        { name: "id", type: "string", required: true, unique: true },
        { name: "type", type: "enum", required: true, enumValues: ["call", "email", "meeting", "note", "task"] },
        { name: "contactId", type: "ref", required: false, refEntity: "Contact" },
        { name: "dealId", type: "ref", required: false, refEntity: "Deal" },
        { name: "userId", type: "ref", required: true, refEntity: "User" },
        { name: "subject", type: "string", required: true },
        { name: "body", type: "string", required: false },
        { name: "dueDate", type: "datetime", required: false },
        { name: "completed", type: "boolean", required: true, defaultValue: "false" },
      ],
      relationships: [
        { type: "belongs_to", targetEntity: "Contact" },
        { type: "belongs_to", targetEntity: "Deal" },
      ],
      businessRules: ["Activities appear in contact and deal timelines"],
    },
    {
      name: "User",
      description: "Sales team member.",
      fields: [
        { name: "id", type: "string", required: true, unique: true },
        { name: "email", type: "string", required: true, unique: true },
        { name: "name", type: "string", required: true },
        { name: "passwordHash", type: "string", required: true },
        { name: "role", type: "enum", required: true, enumValues: ["admin", "manager", "rep"] },
        { name: "avatar", type: "string", required: false },
      ],
      relationships: [
        { type: "has_many", targetEntity: "Contact" },
        { type: "has_many", targetEntity: "Deal" },
        { type: "has_many", targetEntity: "Activity" },
      ],
      businessRules: [],
    },
  ],
  standardScreens: [
    { name: "Pipeline Board", route: "/pipeline", description: "Kanban board of deals by stage", layout: "dashboard", accessRoles: ["admin", "manager", "rep"], entities: ["Deal", "PipelineStage"] },
    { name: "Contacts List", route: "/contacts", description: "Searchable contact table", layout: "dashboard", accessRoles: ["admin", "manager", "rep"], entities: ["Contact", "Company"] },
    { name: "Contact Detail", route: "/contacts/[id]", description: "Contact info, deals, activity timeline", layout: "dashboard", accessRoles: ["admin", "manager", "rep"], entities: ["Contact", "Deal", "Activity"] },
    { name: "Companies", route: "/companies", description: "Company list and detail", layout: "dashboard", accessRoles: ["admin", "manager", "rep"], entities: ["Company"] },
    { name: "Deal Detail", route: "/deals/[id]", description: "Deal info, stage, activities", layout: "dashboard", accessRoles: ["admin", "manager", "rep"], entities: ["Deal", "Activity", "Contact"] },
    { name: "Reports", route: "/reports", description: "Sales metrics, pipeline value, win rate", layout: "dashboard", accessRoles: ["admin", "manager"], entities: ["Deal", "Activity"] },
    { name: "Settings", route: "/settings", description: "Pipeline config, team, integrations", layout: "dashboard", accessRoles: ["admin"], entities: ["Pipeline", "PipelineStage", "User"] },
  ],
  standardApiEndpoints: [
    { method: "GET", path: "/api/contacts", description: "List contacts", entity: "Contact", authRequired: true },
    { method: "POST", path: "/api/contacts", description: "Create contact", entity: "Contact", authRequired: true },
    { method: "GET", path: "/api/contacts/:id", description: "Get contact", entity: "Contact", authRequired: true },
    { method: "PUT", path: "/api/contacts/:id", description: "Update contact", entity: "Contact", authRequired: true },
    { method: "GET", path: "/api/deals", description: "List deals", entity: "Deal", authRequired: true },
    { method: "POST", path: "/api/deals", description: "Create deal", entity: "Deal", authRequired: true },
    { method: "PATCH", path: "/api/deals/:id/stage", description: "Move deal stage", entity: "Deal", authRequired: true },
    { method: "GET", path: "/api/pipelines", description: "List pipelines", entity: "Pipeline", authRequired: true },
    { method: "POST", path: "/api/activities", description: "Log activity", entity: "Activity", authRequired: true },
    { method: "GET", path: "/api/contacts/:id/activities", description: "Contact activities", entity: "Activity", authRequired: true },
  ],
  standardRoles: [
    { name: "admin", description: "Full CRM access and settings", permissions: ["manage:all"] },
    { name: "manager", description: "Team management and reporting", permissions: ["read:all-data", "manage:team-data", "read:reports"] },
    { name: "rep", description: "Sales representative", permissions: ["manage:own-contacts", "manage:own-deals", "manage:own-activities"] },
  ],
  standardBusinessRules: [
    { entity: "Deal", rule: "Moving to 'Won' stage auto-updates contact to 'customer' status", type: "workflow" },
    { entity: "Deal", rule: "Deal probability auto-set from pipeline stage", type: "computation" },
    { entity: "Contact", rule: "Reps see only their assigned contacts unless manager/admin", type: "constraint" },
    { entity: "Activity", rule: "Overdue tasks appear in dashboard alerts", type: "workflow" },
  ],
  deduplicationRules: [
    "Contact and company detail pages share the same timeline component",
    "Pipeline board uses a generic Kanban component configurable per pipeline",
    "Activity creation modal is the same component used from contacts, deals, and dashboard",
  ],
  antiPatterns: [
    "Separate pages for each activity type",
    "Client-side pipeline stage calculations",
    "Duplicating contact info inside deal records",
  ],
};
