import type { PatternDefinition } from "../../types";

export const ecommercePattern: PatternDefinition = {
  id: "ecommerce",
  name: "E-Commerce",
  description:
    "Online store with product catalog, cart, checkout, orders, and payment processing.",
  keywords: [
    "shop", "store", "product", "cart", "checkout", "order", "payment",
    "inventory", "catalog", "e-commerce", "ecommerce", "buy", "sell",
    "shipping", "wishlist", "review", "sku", "price",
  ],
  standardEntities: [
    {
      name: "Product",
      description: "A purchasable item in the store catalog.",
      fields: [
        { name: "id", type: "string", required: true, unique: true },
        { name: "name", type: "string", required: true },
        { name: "slug", type: "string", required: true, unique: true },
        { name: "description", type: "string", required: true },
        { name: "price", type: "number", required: true },
        { name: "compareAtPrice", type: "number", required: false },
        { name: "sku", type: "string", required: false, unique: true },
        { name: "stock", type: "number", required: true, defaultValue: "0" },
        { name: "images", type: "array", required: false },
        { name: "categoryId", type: "ref", required: true, refEntity: "Category" },
        { name: "status", type: "enum", required: true, enumValues: ["draft", "active", "archived"] },
        { name: "tags", type: "array", required: false },
      ],
      relationships: [
        { type: "belongs_to", targetEntity: "Category" },
        { type: "has_many", targetEntity: "Review" },
        { type: "has_many", targetEntity: "OrderItem" },
      ],
      businessRules: [
        "Stock cannot go below 0",
        "Price must be > 0",
        "Slug auto-generated from name if not provided",
        "Archived products hidden from storefront but visible in admin",
      ],
    },
    {
      name: "Category",
      description: "Product category for organizing the catalog.",
      fields: [
        { name: "id", type: "string", required: true, unique: true },
        { name: "name", type: "string", required: true },
        { name: "slug", type: "string", required: true, unique: true },
        { name: "parentId", type: "ref", required: false, refEntity: "Category" },
        { name: "image", type: "string", required: false },
        { name: "sortOrder", type: "number", required: false, defaultValue: "0" },
      ],
      relationships: [
        { type: "has_many", targetEntity: "Product" },
        { type: "belongs_to", targetEntity: "Category", foreignKey: "parentId" },
      ],
      businessRules: [
        "Categories can be nested up to 3 levels",
        "Deleting a category reassigns products to parent category",
      ],
    },
    {
      name: "Cart",
      description: "Shopping cart holding items before checkout.",
      fields: [
        { name: "id", type: "string", required: true, unique: true },
        { name: "userId", type: "ref", required: false, refEntity: "User" },
        { name: "sessionId", type: "string", required: false },
        { name: "items", type: "array", required: true },
        { name: "subtotal", type: "number", required: true },
        { name: "expiresAt", type: "datetime", required: false },
      ],
      relationships: [
        { type: "belongs_to", targetEntity: "User" },
      ],
      businessRules: [
        "Guest carts use sessionId, authenticated carts use userId",
        "Cart merges on login if guest cart has items",
        "Cart items validate against current stock",
        "Abandoned carts expire after 30 days",
      ],
    },
    {
      name: "Order",
      description: "A confirmed purchase with payment and fulfillment tracking.",
      fields: [
        { name: "id", type: "string", required: true, unique: true },
        { name: "orderNumber", type: "string", required: true, unique: true },
        { name: "userId", type: "ref", required: true, refEntity: "User" },
        { name: "status", type: "enum", required: true, enumValues: ["pending", "paid", "processing", "shipped", "delivered", "cancelled", "refunded"] },
        { name: "items", type: "array", required: true },
        { name: "subtotal", type: "number", required: true },
        { name: "tax", type: "number", required: true },
        { name: "shipping", type: "number", required: true },
        { name: "total", type: "number", required: true },
        { name: "shippingAddress", type: "object", required: true },
        { name: "paymentMethod", type: "string", required: true },
        { name: "paymentId", type: "string", required: false },
        { name: "trackingNumber", type: "string", required: false },
        { name: "notes", type: "string", required: false },
      ],
      relationships: [
        { type: "belongs_to", targetEntity: "User" },
        { type: "has_many", targetEntity: "OrderItem" },
      ],
      businessRules: [
        "Status transitions: pending→paid→processing→shipped→delivered",
        "Cancel allowed from: pending, paid (triggers refund)",
        "Stock reserved on order creation, released on cancellation",
        "Order number auto-generated: ORD-YYYYMMDD-XXXX",
      ],
      indexes: ["userId", "status", "createdAt", "orderNumber"],
    },
    {
      name: "User",
      description: "Store customer or admin user.",
      fields: [
        { name: "id", type: "string", required: true, unique: true },
        { name: "email", type: "string", required: true, unique: true },
        { name: "name", type: "string", required: true },
        { name: "passwordHash", type: "string", required: true },
        { name: "role", type: "enum", required: true, enumValues: ["customer", "admin"] },
        { name: "avatar", type: "string", required: false },
        { name: "addresses", type: "array", required: false },
        { name: "phone", type: "string", required: false },
      ],
      relationships: [
        { type: "has_many", targetEntity: "Order" },
        { type: "has_many", targetEntity: "Review" },
        { type: "has_one", targetEntity: "Cart" },
      ],
      businessRules: [
        "Email must be unique and verified",
        "Password minimum 8 characters with complexity rules",
        "Admin role assigned manually, not self-registerable",
      ],
    },
    {
      name: "Review",
      description: "Product review with rating.",
      fields: [
        { name: "id", type: "string", required: true, unique: true },
        { name: "productId", type: "ref", required: true, refEntity: "Product" },
        { name: "userId", type: "ref", required: true, refEntity: "User" },
        { name: "rating", type: "number", required: true },
        { name: "title", type: "string", required: false },
        { name: "body", type: "string", required: true },
        { name: "verified", type: "boolean", required: true, defaultValue: "false" },
      ],
      relationships: [
        { type: "belongs_to", targetEntity: "Product" },
        { type: "belongs_to", targetEntity: "User" },
      ],
      businessRules: [
        "Rating must be 1-5",
        "One review per user per product",
        "Verified badge if user purchased the product",
      ],
    },
  ],
  standardScreens: [
    { name: "Home / Landing", route: "/", description: "Hero, featured products, categories", layout: "public", accessRoles: ["*"], entities: ["Product", "Category"] },
    { name: "Product Listing", route: "/shop", description: "Filterable product grid with pagination", layout: "public", accessRoles: ["*"], entities: ["Product", "Category"] },
    { name: "Product Detail", route: "/shop/[slug]", description: "Product info, images, reviews, add to cart", layout: "public", accessRoles: ["*"], entities: ["Product", "Review"] },
    { name: "Cart", route: "/cart", description: "Cart items, quantity controls, subtotal", layout: "public", accessRoles: ["*"], entities: ["Cart", "Product"] },
    { name: "Checkout", route: "/checkout", description: "Shipping, payment, order summary", layout: "public", accessRoles: ["customer", "admin"], entities: ["Cart", "Order"] },
    { name: "Order History", route: "/account/orders", description: "Past orders with status", layout: "dashboard", accessRoles: ["customer"], entities: ["Order"] },
    { name: "Order Detail", route: "/account/orders/[id]", description: "Order details, tracking, items", layout: "dashboard", accessRoles: ["customer"], entities: ["Order"] },
    { name: "Login", route: "/login", description: "Email/password login", layout: "auth", accessRoles: ["*"], entities: ["User"] },
    { name: "Register", route: "/register", description: "Create account form", layout: "auth", accessRoles: ["*"], entities: ["User"] },
    { name: "Admin Dashboard", route: "/admin", description: "Sales stats, recent orders, low stock", layout: "admin", accessRoles: ["admin"], entities: ["Order", "Product"] },
    { name: "Admin Products", route: "/admin/products", description: "Product CRUD table", layout: "admin", accessRoles: ["admin"], entities: ["Product", "Category"] },
    { name: "Admin Orders", route: "/admin/orders", description: "Order management table", layout: "admin", accessRoles: ["admin"], entities: ["Order"] },
  ],
  standardApiEndpoints: [
    { method: "GET", path: "/api/products", description: "List products (paginated, filterable)", entity: "Product", authRequired: false },
    { method: "GET", path: "/api/products/:slug", description: "Get product detail", entity: "Product", authRequired: false },
    { method: "POST", path: "/api/products", description: "Create product", entity: "Product", authRequired: true, roles: ["admin"] },
    { method: "PUT", path: "/api/products/:id", description: "Update product", entity: "Product", authRequired: true, roles: ["admin"] },
    { method: "DELETE", path: "/api/products/:id", description: "Delete product", entity: "Product", authRequired: true, roles: ["admin"] },
    { method: "GET", path: "/api/categories", description: "List categories (tree)", entity: "Category", authRequired: false },
    { method: "GET", path: "/api/cart", description: "Get current cart", entity: "Cart", authRequired: false },
    { method: "POST", path: "/api/cart/items", description: "Add item to cart", entity: "Cart", authRequired: false },
    { method: "PUT", path: "/api/cart/items/:id", description: "Update cart item quantity", entity: "Cart", authRequired: false },
    { method: "DELETE", path: "/api/cart/items/:id", description: "Remove cart item", entity: "Cart", authRequired: false },
    { method: "POST", path: "/api/orders", description: "Create order from cart", entity: "Order", authRequired: true },
    { method: "GET", path: "/api/orders", description: "List user orders", entity: "Order", authRequired: true },
    { method: "GET", path: "/api/orders/:id", description: "Get order detail", entity: "Order", authRequired: true },
    { method: "PATCH", path: "/api/orders/:id/status", description: "Update order status", entity: "Order", authRequired: true, roles: ["admin"] },
    { method: "POST", path: "/api/auth/login", description: "Login", entity: "User", authRequired: false },
    { method: "POST", path: "/api/auth/register", description: "Register", entity: "User", authRequired: false },
    { method: "POST", path: "/api/reviews", description: "Create review", entity: "Review", authRequired: true },
    { method: "GET", path: "/api/products/:id/reviews", description: "List product reviews", entity: "Review", authRequired: false },
  ],
  standardRoles: [
    { name: "customer", description: "Registered store customer", permissions: ["read:products", "manage:cart", "manage:own-orders", "manage:own-reviews", "manage:own-profile"] },
    { name: "admin", description: "Store administrator with full access", permissions: ["manage:products", "manage:categories", "manage:orders", "manage:users", "manage:reviews", "view:analytics"] },
  ],
  standardBusinessRules: [
    { entity: "Product", rule: "Stock cannot go below 0", type: "constraint" },
    { entity: "Product", rule: "Price must be positive", type: "validation" },
    { entity: "Order", rule: "Status transitions must follow: pending→paid→processing→shipped→delivered", type: "workflow" },
    { entity: "Order", rule: "Cancellation triggers stock release and refund", type: "workflow" },
    { entity: "Cart", rule: "Cart items validate against current stock before checkout", type: "validation" },
    { entity: "Review", rule: "One review per user per product", type: "constraint" },
    { entity: "User", rule: "Email must be verified before placing orders", type: "constraint" },
  ],
  deduplicationRules: [
    "/shop?category=X is ONE dynamic route with filters, not separate category pages",
    "Admin product/order lists share a DataTable component with different configs",
    "Customer and admin order views share the same OrderDetail component with role-based fields",
    "Product card component is reused across home, shop, and search results",
  ],
  antiPatterns: [
    "Separate pages per category (/shop/women, /shop/men) instead of query params",
    "Inline price calculations instead of a centralized pricing service",
    "Direct database queries in components/pages",
    "Hardcoded tax rates instead of configurable rules",
    "Cart stored only in client state (loses on refresh)",
  ],
};
