import type { PatternDefinition } from "../../types";

export const lmsPattern: PatternDefinition = {
  id: "lms",
  name: "Learning Management System",
  description: "Online learning platform with courses, lessons, quizzes, progress tracking, and certificates.",
  keywords: ["lms", "course", "lesson", "quiz", "student", "instructor", "learning", "education", "certificate", "progress", "enrollment"],
  standardEntities: [
    {
      name: "Course",
      description: "A learning course with modules and lessons.",
      fields: [
        { name: "id", type: "string", required: true, unique: true },
        { name: "title", type: "string", required: true },
        { name: "slug", type: "string", required: true, unique: true },
        { name: "description", type: "string", required: true },
        { name: "instructorId", type: "ref", required: true, refEntity: "User" },
        { name: "coverImage", type: "string", required: false },
        { name: "price", type: "number", required: false },
        { name: "level", type: "enum", required: true, enumValues: ["beginner", "intermediate", "advanced"] },
        { name: "categoryId", type: "ref", required: true, refEntity: "CourseCategory" },
        { name: "status", type: "enum", required: true, enumValues: ["draft", "published", "archived"] },
        { name: "enrollmentCount", type: "number", required: true, defaultValue: "0" },
        { name: "rating", type: "number", required: false },
        { name: "prerequisites", type: "array", required: false },
        { name: "estimatedDuration", type: "number", required: false, description: "Total hours" },
      ],
      relationships: [
        { type: "belongs_to", targetEntity: "User" },
        { type: "has_many", targetEntity: "Module" },
        { type: "has_many", targetEntity: "Enrollment" },
      ],
      businessRules: ["Published courses cannot change structure (add new version instead)", "Free courses have price = 0 or null"],
    },
    {
      name: "Module",
      description: "A section within a course containing lessons.",
      fields: [
        { name: "id", type: "string", required: true, unique: true },
        { name: "courseId", type: "ref", required: true, refEntity: "Course" },
        { name: "title", type: "string", required: true },
        { name: "sortOrder", type: "number", required: true },
      ],
      relationships: [
        { type: "belongs_to", targetEntity: "Course" },
        { type: "has_many", targetEntity: "Lesson" },
      ],
      businessRules: [],
    },
    {
      name: "Lesson",
      description: "Individual lesson with content (video, text, quiz).",
      fields: [
        { name: "id", type: "string", required: true, unique: true },
        { name: "moduleId", type: "ref", required: true, refEntity: "Module" },
        { name: "title", type: "string", required: true },
        { name: "type", type: "enum", required: true, enumValues: ["video", "text", "quiz", "assignment"] },
        { name: "content", type: "object", required: true },
        { name: "duration", type: "number", required: false, description: "Minutes" },
        { name: "sortOrder", type: "number", required: true },
        { name: "isFree", type: "boolean", required: true, defaultValue: "false" },
      ],
      relationships: [
        { type: "belongs_to", targetEntity: "Module" },
      ],
      businessRules: ["Free lessons accessible without enrollment"],
    },
    {
      name: "Enrollment",
      description: "Student's enrollment in a course.",
      fields: [
        { name: "id", type: "string", required: true, unique: true },
        { name: "userId", type: "ref", required: true, refEntity: "User" },
        { name: "courseId", type: "ref", required: true, refEntity: "Course" },
        { name: "progress", type: "number", required: true, defaultValue: "0", description: "Percentage 0-100" },
        { name: "completedLessons", type: "array", required: true },
        { name: "status", type: "enum", required: true, enumValues: ["active", "completed", "expired"] },
        { name: "enrolledAt", type: "datetime", required: true },
        { name: "completedAt", type: "datetime", required: false },
        { name: "certificateId", type: "ref", required: false, refEntity: "Certificate" },
      ],
      relationships: [
        { type: "belongs_to", targetEntity: "User" },
        { type: "belongs_to", targetEntity: "Course" },
        { type: "has_one", targetEntity: "Certificate" },
      ],
      businessRules: ["Progress = completed lessons / total lessons × 100", "Certificate auto-issued at 100% completion"],
    },
    {
      name: "Certificate",
      description: "Completion certificate.",
      fields: [
        { name: "id", type: "string", required: true, unique: true },
        { name: "enrollmentId", type: "ref", required: true, refEntity: "Enrollment" },
        { name: "userId", type: "ref", required: true, refEntity: "User" },
        { name: "courseId", type: "ref", required: true, refEntity: "Course" },
        { name: "issuedAt", type: "datetime", required: true },
        { name: "verificationCode", type: "string", required: true, unique: true },
      ],
      relationships: [
        { type: "belongs_to", targetEntity: "Enrollment" },
      ],
      businessRules: ["Unique verification code for public verification", "Cannot be revoked once issued"],
    },
    {
      name: "User",
      description: "Student, instructor, or admin.",
      fields: [
        { name: "id", type: "string", required: true, unique: true },
        { name: "email", type: "string", required: true, unique: true },
        { name: "name", type: "string", required: true },
        { name: "passwordHash", type: "string", required: true },
        { name: "role", type: "enum", required: true, enumValues: ["student", "instructor", "admin"] },
        { name: "avatar", type: "string", required: false },
        { name: "bio", type: "string", required: false },
      ],
      relationships: [
        { type: "has_many", targetEntity: "Enrollment" },
        { type: "has_many", targetEntity: "Course" },
      ],
      businessRules: [],
    },
    {
      name: "CourseCategory",
      description: "Category for organizing courses.",
      fields: [
        { name: "id", type: "string", required: true, unique: true },
        { name: "name", type: "string", required: true },
        { name: "slug", type: "string", required: true, unique: true },
      ],
      relationships: [{ type: "has_many", targetEntity: "Course" }],
      businessRules: [],
    },
  ],
  standardScreens: [
    { name: "Course Catalog", route: "/courses", description: "Browse/filter courses by category, level", layout: "public", accessRoles: ["*"], entities: ["Course", "CourseCategory"] },
    { name: "Course Detail", route: "/courses/[slug]", description: "Course info, curriculum, enroll button", layout: "public", accessRoles: ["*"], entities: ["Course", "Module", "Lesson"] },
    { name: "Lesson Player", route: "/learn/[courseSlug]/[lessonId]", description: "Video/content viewer with sidebar navigation", layout: "learning", accessRoles: ["student"], entities: ["Lesson", "Enrollment"] },
    { name: "My Learning", route: "/my-learning", description: "Enrolled courses with progress", layout: "dashboard", accessRoles: ["student"], entities: ["Enrollment", "Course"] },
    { name: "Certificates", route: "/certificates", description: "Earned certificates", layout: "dashboard", accessRoles: ["student"], entities: ["Certificate"] },
    { name: "Instructor Dashboard", route: "/instructor", description: "My courses, enrollment stats, revenue", layout: "dashboard", accessRoles: ["instructor"], entities: ["Course", "Enrollment"] },
    { name: "Course Builder", route: "/instructor/courses/[id]/edit", description: "Create/edit course with modules and lessons", layout: "dashboard", accessRoles: ["instructor"], entities: ["Course", "Module", "Lesson"] },
    { name: "Admin Dashboard", route: "/admin", description: "Platform stats, user management", layout: "admin", accessRoles: ["admin"], entities: ["Course", "User", "Enrollment"] },
  ],
  standardApiEndpoints: [
    { method: "GET", path: "/api/courses", description: "List published courses", entity: "Course", authRequired: false },
    { method: "GET", path: "/api/courses/:slug", description: "Get course detail with curriculum", entity: "Course", authRequired: false },
    { method: "POST", path: "/api/courses", description: "Create course", entity: "Course", authRequired: true, roles: ["instructor"] },
    { method: "PUT", path: "/api/courses/:id", description: "Update course", entity: "Course", authRequired: true, roles: ["instructor"] },
    { method: "POST", path: "/api/enrollments", description: "Enroll in course", entity: "Enrollment", authRequired: true },
    { method: "PATCH", path: "/api/enrollments/:id/progress", description: "Update lesson progress", entity: "Enrollment", authRequired: true },
    { method: "GET", path: "/api/enrollments", description: "My enrollments", entity: "Enrollment", authRequired: true },
    { method: "GET", path: "/api/lessons/:id", description: "Get lesson content", entity: "Lesson", authRequired: true },
    { method: "GET", path: "/api/certificates/:code", description: "Verify certificate", entity: "Certificate", authRequired: false },
  ],
  standardRoles: [
    { name: "student", description: "Can browse, enroll, and learn", permissions: ["read:courses", "manage:own-enrollments", "read:own-certificates"] },
    { name: "instructor", description: "Can create and manage courses", permissions: ["manage:own-courses", "read:own-enrollments", "read:own-revenue"] },
    { name: "admin", description: "Full platform access", permissions: ["manage:all"] },
  ],
  standardBusinessRules: [
    { entity: "Enrollment", rule: "Progress auto-calculated from completed lessons", type: "computation" },
    { entity: "Certificate", rule: "Auto-issued when enrollment reaches 100% progress", type: "workflow" },
    { entity: "Lesson", rule: "Free preview lessons accessible without enrollment", type: "constraint" },
    { entity: "Course", rule: "Prerequisites must be completed before enrollment", type: "constraint" },
  ],
  deduplicationRules: [
    "CourseCard component reused in catalog, my-learning, and instructor dashboard",
    "Lesson sidebar navigation is same component for student and instructor preview",
    "Progress bar component reused on course card, my-learning page, and lesson player",
  ],
  antiPatterns: [
    "Storing progress as a list of timestamps instead of lesson completion flags",
    "Loading entire course content at once instead of per-lesson",
    "Quiz results stored only on client side",
    "Certificate generation on client side",
  ],
};
