import type { PatternDefinition } from "../../types";

export const marketplacePattern: PatternDefinition = {
  id: "marketplace",
  name: "Marketplace",
  description:
    "Two-sided marketplace connecting sellers/vendors with buyers, with listings, transactions, and commissions.",
  keywords: [
    "marketplace", "vendor", "seller", "buyer", "listing", "commission",
    "payout", "dispute", "multi-vendor", "two-sided", "platform",
  ],
  standardEntities: [
    {
      name: "User",
      description: "Platform user who can be a buyer, seller, or admin.",
      fields: [
        { name: "id", type: "string", required: true, unique: true },
        { name: "email", type: "string", required: true, unique: true },
        { name: "name", type: "string", required: true },
        { name: "passwordHash", type: "string", required: true },
        { name: "role", type: "enum", required: true, enumValues: ["buyer", "seller", "admin"] },
        { name: "avatar", type: "string", required: false },
        { name: "verified", type: "boolean", required: true, defaultValue: "false" },
      ],
      relationships: [
        { type: "has_one", targetEntity: "VendorProfile" },
        { type: "has_many", targetEntity: "Order" },
      ],
      businessRules: ["Sellers require profile verification before listing"],
    },
    {
      name: "VendorProfile",
      description: "Seller's public storefront profile.",
      fields: [
        { name: "id", type: "string", required: true, unique: true },
        { name: "userId", type: "ref", required: true, refEntity: "User" },
        { name: "storeName", type: "string", required: true },
        { name: "slug", type: "string", required: true, unique: true },
        { name: "description", type: "string", required: false },
        { name: "logo", type: "string", required: false },
        { name: "rating", type: "number", required: false },
        { name: "totalSales", type: "number", required: true, defaultValue: "0" },
        { name: "commissionRate", type: "number", required: true },
        { name: "payoutMethod", type: "object", required: false },
        { name: "verificationStatus", type: "enum", required: true, enumValues: ["pending", "approved", "rejected"] },
      ],
      relationships: [
        { type: "belongs_to", targetEntity: "User" },
        { type: "has_many", targetEntity: "Listing" },
      ],
      businessRules: ["Commission rate defaults to platform rate, can be custom per vendor"],
    },
    {
      name: "Listing",
      description: "An item or service listed for sale by a vendor.",
      fields: [
        { name: "id", type: "string", required: true, unique: true },
        { name: "vendorId", type: "ref", required: true, refEntity: "VendorProfile" },
        { name: "title", type: "string", required: true },
        { name: "slug", type: "string", required: true },
        { name: "description", type: "string", required: true },
        { name: "price", type: "number", required: true },
        { name: "categoryId", type: "ref", required: true, refEntity: "Category" },
        { name: "images", type: "array", required: false },
        { name: "status", type: "enum", required: true, enumValues: ["draft", "pending_review", "active", "paused", "rejected"] },
        { name: "stock", type: "number", required: false },
      ],
      relationships: [
        { type: "belongs_to", targetEntity: "VendorProfile" },
        { type: "belongs_to", targetEntity: "Category" },
      ],
      businessRules: [
        "New listings require admin approval",
        "Rejected listings include reason and can be resubmitted",
      ],
    },
    {
      name: "Category",
      description: "Listing category.",
      fields: [
        { name: "id", type: "string", required: true, unique: true },
        { name: "name", type: "string", required: true },
        { name: "slug", type: "string", required: true, unique: true },
        { name: "parentId", type: "ref", required: false, refEntity: "Category" },
      ],
      relationships: [
        { type: "has_many", targetEntity: "Listing" },
      ],
      businessRules: [],
    },
    {
      name: "Order",
      description: "A transaction between buyer and seller.",
      fields: [
        { name: "id", type: "string", required: true, unique: true },
        { name: "buyerId", type: "ref", required: true, refEntity: "User" },
        { name: "vendorId", type: "ref", required: true, refEntity: "VendorProfile" },
        { name: "listingId", type: "ref", required: true, refEntity: "Listing" },
        { name: "amount", type: "number", required: true },
        { name: "platformFee", type: "number", required: true },
        { name: "vendorPayout", type: "number", required: true },
        { name: "status", type: "enum", required: true, enumValues: ["pending", "paid", "in_progress", "completed", "disputed", "refunded", "cancelled"] },
        { name: "paymentId", type: "string", required: false },
      ],
      relationships: [
        { type: "belongs_to", targetEntity: "User" },
        { type: "belongs_to", targetEntity: "VendorProfile" },
        { type: "belongs_to", targetEntity: "Listing" },
      ],
      businessRules: [
        "Platform fee calculated as vendorCommissionRate * amount",
        "Funds held in escrow until order completed",
        "Dispute window: 14 days after completion",
      ],
    },
    {
      name: "Dispute",
      description: "A dispute between buyer and seller.",
      fields: [
        { name: "id", type: "string", required: true, unique: true },
        { name: "orderId", type: "ref", required: true, refEntity: "Order" },
        { name: "raisedBy", type: "ref", required: true, refEntity: "User" },
        { name: "reason", type: "string", required: true },
        { name: "status", type: "enum", required: true, enumValues: ["open", "under_review", "resolved_buyer", "resolved_seller", "closed"] },
        { name: "resolution", type: "string", required: false },
      ],
      relationships: [
        { type: "belongs_to", targetEntity: "Order" },
      ],
      businessRules: [
        "Admin resolves disputes",
        "Resolution can trigger full or partial refund",
      ],
    },
  ],
  standardScreens: [
    { name: "Home / Browse", route: "/", description: "Featured listings, categories, search", layout: "public", accessRoles: ["*"], entities: ["Listing", "Category"] },
    { name: "Search Results", route: "/search", description: "Filtered listing results", layout: "public", accessRoles: ["*"], entities: ["Listing", "Category"] },
    { name: "Listing Detail", route: "/listing/[slug]", description: "Listing info, vendor info, buy button", layout: "public", accessRoles: ["*"], entities: ["Listing", "VendorProfile"] },
    { name: "Vendor Store", route: "/vendor/[slug]", description: "Vendor profile, their listings", layout: "public", accessRoles: ["*"], entities: ["VendorProfile", "Listing"] },
    { name: "Buyer Dashboard", route: "/dashboard", description: "My orders, saved items", layout: "dashboard", accessRoles: ["buyer"], entities: ["Order"] },
    { name: "Seller Dashboard", route: "/seller", description: "Sales stats, listings, payouts", layout: "dashboard", accessRoles: ["seller"], entities: ["Listing", "Order", "VendorProfile"] },
    { name: "Seller Listings", route: "/seller/listings", description: "Manage listings CRUD", layout: "dashboard", accessRoles: ["seller"], entities: ["Listing"] },
    { name: "Admin Dashboard", route: "/admin", description: "Platform stats, pending reviews", layout: "admin", accessRoles: ["admin"], entities: ["Listing", "Order", "Dispute"] },
    { name: "Admin Listing Review", route: "/admin/reviews", description: "Approve/reject listings", layout: "admin", accessRoles: ["admin"], entities: ["Listing"] },
    { name: "Admin Disputes", route: "/admin/disputes", description: "Dispute resolution", layout: "admin", accessRoles: ["admin"], entities: ["Dispute", "Order"] },
  ],
  standardApiEndpoints: [
    { method: "GET", path: "/api/listings", description: "Browse listings", entity: "Listing", authRequired: false },
    { method: "GET", path: "/api/listings/:slug", description: "Get listing detail", entity: "Listing", authRequired: false },
    { method: "POST", path: "/api/listings", description: "Create listing", entity: "Listing", authRequired: true, roles: ["seller"] },
    { method: "PUT", path: "/api/listings/:id", description: "Update listing", entity: "Listing", authRequired: true, roles: ["seller"] },
    { method: "POST", path: "/api/orders", description: "Create order (buy)", entity: "Order", authRequired: true },
    { method: "GET", path: "/api/orders", description: "List my orders", entity: "Order", authRequired: true },
    { method: "PATCH", path: "/api/orders/:id/status", description: "Update order status", entity: "Order", authRequired: true },
    { method: "GET", path: "/api/vendors/:slug", description: "Get vendor profile", entity: "VendorProfile", authRequired: false },
    { method: "POST", path: "/api/disputes", description: "Raise dispute", entity: "Dispute", authRequired: true },
    { method: "PATCH", path: "/api/admin/listings/:id/review", description: "Approve/reject listing", entity: "Listing", authRequired: true, roles: ["admin"] },
    { method: "PATCH", path: "/api/admin/disputes/:id", description: "Resolve dispute", entity: "Dispute", authRequired: true, roles: ["admin"] },
  ],
  standardRoles: [
    { name: "buyer", description: "Can browse, purchase, and raise disputes", permissions: ["read:listings", "manage:own-orders", "manage:disputes"] },
    { name: "seller", description: "Can list items, manage orders, view payouts", permissions: ["manage:own-listings", "manage:vendor-orders", "read:payouts"] },
    { name: "admin", description: "Platform administrator", permissions: ["manage:all-listings", "manage:disputes", "manage:vendors", "manage:payouts", "view:analytics"] },
  ],
  standardBusinessRules: [
    { entity: "Listing", rule: "New listings require admin approval before going live", type: "workflow" },
    { entity: "Order", rule: "Funds held in escrow until buyer confirms receipt", type: "workflow" },
    { entity: "Order", rule: "Platform fee = vendor commission rate × order amount", type: "computation" },
    { entity: "Dispute", rule: "14-day dispute window after order completion", type: "constraint" },
    { entity: "VendorProfile", rule: "Sellers must be verified before first listing goes live", type: "constraint" },
  ],
  deduplicationRules: [
    "Buyer and seller dashboards share layout with role-based navigation items",
    "Listing card component reused across home, search, vendor store, and admin",
    "Order detail page shared between buyer and seller with role-based actions",
    "Search/browse uses one route with query params for category, price, vendor filters",
  ],
  antiPatterns: [
    "Separate codebases for buyer and seller portals",
    "Bypassing escrow for direct vendor payment",
    "Allowing vendors to approve their own listings",
    "Client-side commission calculations",
  ],
};
