import type { PatternDefinition } from "../../types";

export const saasPattern: PatternDefinition = {
  id: "saas",
  name: "SaaS Platform",
  description:
    "Multi-tenant SaaS application with subscriptions, billing, team management, and usage analytics.",
  keywords: [
    "saas", "subscription", "plan", "billing", "tenant", "organization",
    "team", "workspace", "dashboard", "analytics", "multi-tenant", "pricing",
    "trial", "upgrade",
  ],
  standardEntities: [
    {
      name: "Organization",
      description: "A tenant/workspace in the multi-tenant system.",
      fields: [
        { name: "id", type: "string", required: true, unique: true },
        { name: "name", type: "string", required: true },
        { name: "slug", type: "string", required: true, unique: true },
        { name: "planId", type: "ref", required: true, refEntity: "Plan" },
        { name: "subscriptionStatus", type: "enum", required: true, enumValues: ["trial", "active", "past_due", "cancelled", "expired"] },
        { name: "trialEndsAt", type: "datetime", required: false },
        { name: "settings", type: "object", required: false },
        { name: "logo", type: "string", required: false },
      ],
      relationships: [
        { type: "has_many", targetEntity: "Member" },
        { type: "belongs_to", targetEntity: "Plan" },
        { type: "has_many", targetEntity: "Invoice" },
      ],
      businessRules: [
        "14-day free trial on creation",
        "Downgrade only at billing period end",
        "Data retained 30 days after cancellation",
      ],
    },
    {
      name: "User",
      description: "Individual user who can belong to multiple organizations.",
      fields: [
        { name: "id", type: "string", required: true, unique: true },
        { name: "email", type: "string", required: true, unique: true },
        { name: "name", type: "string", required: true },
        { name: "passwordHash", type: "string", required: true },
        { name: "avatar", type: "string", required: false },
        { name: "emailVerified", type: "boolean", required: true, defaultValue: "false" },
      ],
      relationships: [
        { type: "has_many", targetEntity: "Member" },
      ],
      businessRules: [
        "Email must be verified",
        "User can belong to multiple organizations",
      ],
    },
    {
      name: "Member",
      description: "A user's membership in an organization with a role.",
      fields: [
        { name: "id", type: "string", required: true, unique: true },
        { name: "userId", type: "ref", required: true, refEntity: "User" },
        { name: "organizationId", type: "ref", required: true, refEntity: "Organization" },
        { name: "role", type: "enum", required: true, enumValues: ["owner", "admin", "member", "viewer"] },
        { name: "invitedBy", type: "ref", required: false, refEntity: "User" },
        { name: "joinedAt", type: "datetime", required: true },
      ],
      relationships: [
        { type: "belongs_to", targetEntity: "User" },
        { type: "belongs_to", targetEntity: "Organization" },
      ],
      businessRules: [
        "One owner per organization",
        "Member count limited by plan",
        "Owner cannot be removed without transferring ownership",
      ],
    },
    {
      name: "Plan",
      description: "Subscription plan with features and limits.",
      fields: [
        { name: "id", type: "string", required: true, unique: true },
        { name: "name", type: "string", required: true },
        { name: "slug", type: "string", required: true, unique: true },
        { name: "price", type: "number", required: true },
        { name: "interval", type: "enum", required: true, enumValues: ["monthly", "yearly"] },
        { name: "features", type: "array", required: true },
        { name: "limits", type: "object", required: true },
        { name: "isActive", type: "boolean", required: true, defaultValue: "true" },
        { name: "sortOrder", type: "number", required: false },
      ],
      relationships: [
        { type: "has_many", targetEntity: "Organization" },
      ],
      businessRules: [
        "Yearly plans get 20% discount",
        "Enterprise plan has custom pricing",
        "Plan limits enforced at API level",
      ],
    },
    {
      name: "Invoice",
      description: "Billing invoice for subscription payments.",
      fields: [
        { name: "id", type: "string", required: true, unique: true },
        { name: "organizationId", type: "ref", required: true, refEntity: "Organization" },
        { name: "amount", type: "number", required: true },
        { name: "currency", type: "string", required: true, defaultValue: "usd" },
        { name: "status", type: "enum", required: true, enumValues: ["draft", "open", "paid", "void", "uncollectible"] },
        { name: "periodStart", type: "datetime", required: true },
        { name: "periodEnd", type: "datetime", required: true },
        { name: "paidAt", type: "datetime", required: false },
        { name: "stripeInvoiceId", type: "string", required: false },
      ],
      relationships: [
        { type: "belongs_to", targetEntity: "Organization" },
      ],
      businessRules: [
        "Auto-generated at billing period start",
        "3 retry attempts for failed payments",
        "Account suspended after 3 failed retries",
      ],
    },
  ],
  standardScreens: [
    { name: "Landing / Pricing", route: "/", description: "Hero, features, pricing table, CTA", layout: "public", accessRoles: ["*"], entities: ["Plan"] },
    { name: "Pricing Page", route: "/pricing", description: "Plan comparison table with toggle monthly/yearly", layout: "public", accessRoles: ["*"], entities: ["Plan"] },
    { name: "Login", route: "/login", description: "Email/password + OAuth login", layout: "auth", accessRoles: ["*"], entities: ["User"] },
    { name: "Register", route: "/register", description: "Create account + organization", layout: "auth", accessRoles: ["*"], entities: ["User", "Organization"] },
    { name: "Dashboard", route: "/dashboard", description: "Usage stats, recent activity, quick actions", layout: "dashboard", accessRoles: ["owner", "admin", "member"], entities: ["Organization"] },
    { name: "Settings / General", route: "/settings", description: "Organization name, logo, preferences", layout: "dashboard", accessRoles: ["owner", "admin"], entities: ["Organization"] },
    { name: "Team Management", route: "/settings/team", description: "Member list, invite, role assignment", layout: "dashboard", accessRoles: ["owner", "admin"], entities: ["Member", "User"] },
    { name: "Billing", route: "/settings/billing", description: "Current plan, invoices, payment method", layout: "dashboard", accessRoles: ["owner"], entities: ["Plan", "Invoice", "Organization"] },
    { name: "User Profile", route: "/profile", description: "Personal settings, avatar, password", layout: "dashboard", accessRoles: ["*"], entities: ["User"] },
  ],
  standardApiEndpoints: [
    { method: "POST", path: "/api/auth/login", description: "Login", entity: "User", authRequired: false },
    { method: "POST", path: "/api/auth/register", description: "Register + create org", entity: "User", authRequired: false },
    { method: "GET", path: "/api/organizations/:id", description: "Get organization", entity: "Organization", authRequired: true },
    { method: "PUT", path: "/api/organizations/:id", description: "Update organization", entity: "Organization", authRequired: true, roles: ["owner", "admin"] },
    { method: "GET", path: "/api/organizations/:id/members", description: "List members", entity: "Member", authRequired: true },
    { method: "POST", path: "/api/organizations/:id/members/invite", description: "Invite member", entity: "Member", authRequired: true, roles: ["owner", "admin"] },
    { method: "DELETE", path: "/api/organizations/:orgId/members/:id", description: "Remove member", entity: "Member", authRequired: true, roles: ["owner", "admin"] },
    { method: "GET", path: "/api/plans", description: "List plans", entity: "Plan", authRequired: false },
    { method: "POST", path: "/api/subscriptions", description: "Subscribe to plan", entity: "Organization", authRequired: true, roles: ["owner"] },
    { method: "PUT", path: "/api/subscriptions", description: "Change plan", entity: "Organization", authRequired: true, roles: ["owner"] },
    { method: "DELETE", path: "/api/subscriptions", description: "Cancel subscription", entity: "Organization", authRequired: true, roles: ["owner"] },
    { method: "GET", path: "/api/invoices", description: "List invoices", entity: "Invoice", authRequired: true, roles: ["owner"] },
  ],
  standardRoles: [
    { name: "owner", description: "Organization creator with full access including billing", permissions: ["manage:organization", "manage:billing", "manage:members", "manage:settings", "manage:data"] },
    { name: "admin", description: "Can manage members and settings, no billing", permissions: ["manage:members", "manage:settings", "manage:data"], inheritsFrom: "member" },
    { name: "member", description: "Standard access to features", permissions: ["read:data", "write:data"], inheritsFrom: "viewer" },
    { name: "viewer", description: "Read-only access", permissions: ["read:data"] },
  ],
  standardBusinessRules: [
    { entity: "Organization", rule: "14-day free trial, then subscription required", type: "workflow" },
    { entity: "Organization", rule: "Member count enforced by plan limits", type: "constraint" },
    { entity: "Organization", rule: "Data isolated between tenants", type: "constraint" },
    { entity: "Plan", rule: "Yearly billing gets 20% discount", type: "computation" },
    { entity: "Invoice", rule: "3 retry attempts for failed payments before suspension", type: "workflow" },
    { entity: "Member", rule: "Ownership transfer required before owner can leave", type: "constraint" },
  ],
  deduplicationRules: [
    "Settings pages share a SettingsLayout with tab navigation, not separate layouts",
    "Owner and admin dashboards are the same component with role-based sections",
    "Member invite and role edit use the same form modal",
    "All organization-scoped API routes use the same tenant middleware",
  ],
  antiPatterns: [
    "Separate database per tenant (use row-level isolation instead)",
    "Plan limits checked only in frontend (must be enforced at API level)",
    "Hardcoded plan features instead of configuration-driven",
    "Direct Stripe API calls in controllers (use a billing service layer)",
    "Role checks scattered across components (use a centralized permission hook)",
  ],
};
