import type { PatternDefinition } from "../../types";

export const socialPattern: PatternDefinition = {
  id: "social",
  name: "Social Platform",
  description: "Social network with user profiles, posts, feed, follows, messaging, and notifications.",
  keywords: ["social", "feed", "post", "follow", "like", "comment", "notification", "message", "profile", "friend", "group", "community"],
  standardEntities: [
    {
      name: "User",
      description: "Platform user with profile.",
      fields: [
        { name: "id", type: "string", required: true, unique: true },
        { name: "username", type: "string", required: true, unique: true },
        { name: "email", type: "string", required: true, unique: true },
        { name: "name", type: "string", required: true },
        { name: "passwordHash", type: "string", required: true },
        { name: "avatar", type: "string", required: false },
        { name: "bio", type: "string", required: false },
        { name: "isVerified", type: "boolean", required: true, defaultValue: "false" },
        { name: "followerCount", type: "number", required: true, defaultValue: "0" },
        { name: "followingCount", type: "number", required: true, defaultValue: "0" },
        { name: "role", type: "enum", required: true, enumValues: ["user", "moderator", "admin"] },
      ],
      relationships: [
        { type: "has_many", targetEntity: "Post" },
        { type: "has_many", targetEntity: "Follow" },
        { type: "has_many", targetEntity: "Notification" },
      ],
      businessRules: ["Username immutable after creation", "Follower/following counts denormalized for performance"],
    },
    {
      name: "Post",
      description: "User-created content.",
      fields: [
        { name: "id", type: "string", required: true, unique: true },
        { name: "authorId", type: "ref", required: true, refEntity: "User" },
        { name: "content", type: "string", required: true },
        { name: "media", type: "array", required: false },
        { name: "likeCount", type: "number", required: true, defaultValue: "0" },
        { name: "commentCount", type: "number", required: true, defaultValue: "0" },
        { name: "shareCount", type: "number", required: true, defaultValue: "0" },
        { name: "visibility", type: "enum", required: true, enumValues: ["public", "followers", "private"] },
        { name: "parentId", type: "ref", required: false, refEntity: "Post", description: "For reposts/quotes" },
      ],
      relationships: [
        { type: "belongs_to", targetEntity: "User" },
        { type: "has_many", targetEntity: "Comment" },
        { type: "has_many", targetEntity: "Like" },
      ],
      businessRules: ["Content moderation check before publishing", "Engagement counts denormalized"],
    },
    {
      name: "Comment",
      description: "Comment on a post.",
      fields: [
        { name: "id", type: "string", required: true, unique: true },
        { name: "postId", type: "ref", required: true, refEntity: "Post" },
        { name: "authorId", type: "ref", required: true, refEntity: "User" },
        { name: "content", type: "string", required: true },
        { name: "parentId", type: "ref", required: false, refEntity: "Comment" },
        { name: "likeCount", type: "number", required: true, defaultValue: "0" },
      ],
      relationships: [
        { type: "belongs_to", targetEntity: "Post" },
        { type: "belongs_to", targetEntity: "User" },
      ],
      businessRules: ["Nested comments up to 3 levels"],
    },
    {
      name: "Like",
      description: "Like on a post or comment.",
      fields: [
        { name: "id", type: "string", required: true, unique: true },
        { name: "userId", type: "ref", required: true, refEntity: "User" },
        { name: "postId", type: "ref", required: false, refEntity: "Post" },
        { name: "commentId", type: "ref", required: false, refEntity: "Comment" },
      ],
      relationships: [
        { type: "belongs_to", targetEntity: "User" },
        { type: "belongs_to", targetEntity: "Post" },
      ],
      businessRules: ["One like per user per target (post or comment)"],
    },
    {
      name: "Follow",
      description: "Follow relationship between users.",
      fields: [
        { name: "id", type: "string", required: true, unique: true },
        { name: "followerId", type: "ref", required: true, refEntity: "User" },
        { name: "followingId", type: "ref", required: true, refEntity: "User" },
      ],
      relationships: [],
      businessRules: ["Cannot follow yourself", "Unique constraint on follower+following pair"],
    },
    {
      name: "Notification",
      description: "User notification.",
      fields: [
        { name: "id", type: "string", required: true, unique: true },
        { name: "userId", type: "ref", required: true, refEntity: "User" },
        { name: "type", type: "enum", required: true, enumValues: ["like", "comment", "follow", "mention", "system"] },
        { name: "actorId", type: "ref", required: false, refEntity: "User" },
        { name: "postId", type: "ref", required: false, refEntity: "Post" },
        { name: "message", type: "string", required: true },
        { name: "read", type: "boolean", required: true, defaultValue: "false" },
      ],
      relationships: [{ type: "belongs_to", targetEntity: "User" }],
      businessRules: ["Batch similar notifications (3 people liked your post)", "Unread count cached"],
    },
  ],
  standardScreens: [
    { name: "Feed", route: "/", description: "Chronological/algorithmic feed of followed users' posts", layout: "main", accessRoles: ["user"], entities: ["Post", "User"] },
    { name: "Explore", route: "/explore", description: "Discover trending posts and users", layout: "main", accessRoles: ["*"], entities: ["Post", "User"] },
    { name: "Profile", route: "/[username]", description: "User profile with posts, followers, following", layout: "main", accessRoles: ["*"], entities: ["User", "Post"] },
    { name: "Post Detail", route: "/post/[id]", description: "Single post with full comment thread", layout: "main", accessRoles: ["*"], entities: ["Post", "Comment"] },
    { name: "Notifications", route: "/notifications", description: "Notification feed", layout: "main", accessRoles: ["user"], entities: ["Notification"] },
    { name: "Settings", route: "/settings", description: "Profile, privacy, notification preferences", layout: "main", accessRoles: ["user"], entities: ["User"] },
    { name: "Admin Moderation", route: "/admin/moderation", description: "Reported content review", layout: "admin", accessRoles: ["moderator", "admin"], entities: ["Post", "Comment", "User"] },
  ],
  standardApiEndpoints: [
    { method: "GET", path: "/api/feed", description: "Get personalized feed", entity: "Post", authRequired: true },
    { method: "GET", path: "/api/explore", description: "Trending/discover posts", entity: "Post", authRequired: false },
    { method: "POST", path: "/api/posts", description: "Create post", entity: "Post", authRequired: true },
    { method: "DELETE", path: "/api/posts/:id", description: "Delete post", entity: "Post", authRequired: true },
    { method: "POST", path: "/api/posts/:id/like", description: "Like post", entity: "Like", authRequired: true },
    { method: "DELETE", path: "/api/posts/:id/like", description: "Unlike post", entity: "Like", authRequired: true },
    { method: "POST", path: "/api/posts/:id/comments", description: "Add comment", entity: "Comment", authRequired: true },
    { method: "POST", path: "/api/users/:id/follow", description: "Follow user", entity: "Follow", authRequired: true },
    { method: "DELETE", path: "/api/users/:id/follow", description: "Unfollow user", entity: "Follow", authRequired: true },
    { method: "GET", path: "/api/users/:username", description: "Get user profile", entity: "User", authRequired: false },
    { method: "GET", path: "/api/notifications", description: "Get notifications", entity: "Notification", authRequired: true },
    { method: "PATCH", path: "/api/notifications/read", description: "Mark notifications read", entity: "Notification", authRequired: true },
  ],
  standardRoles: [
    { name: "user", description: "Standard platform user", permissions: ["manage:own-posts", "manage:own-profile", "read:public-content", "interact"] },
    { name: "moderator", description: "Can moderate content", permissions: ["manage:reported-content", "manage:users"], inheritsFrom: "user" },
    { name: "admin", description: "Full platform access", permissions: ["manage:all"] },
  ],
  standardBusinessRules: [
    { entity: "Post", rule: "Feed uses reverse-chronological with engagement weighting", type: "computation" },
    { entity: "Post", rule: "Content moderation scan on creation", type: "workflow" },
    { entity: "Like", rule: "Like/unlike is idempotent", type: "constraint" },
    { entity: "Follow", rule: "Follow triggers notification to target user", type: "workflow" },
    { entity: "Notification", rule: "Similar notifications batched within 1h window", type: "computation" },
  ],
  deduplicationRules: [
    "PostCard component reused in feed, explore, profile, and search",
    "Like button is same component on posts and comments",
    "User avatar+name link is a single UserChip component used everywhere",
    "Comment thread component is recursive, reused in post detail and moderation",
  ],
  antiPatterns: [
    "Loading full follower list on profile page (use count + paginated list)",
    "Real-time like counts via polling (use optimistic UI + websocket)",
    "Storing feed in database per user (compute at read time with caching)",
    "Separate notification endpoints per type",
  ],
};
