import { Account, Transaction, Budget, Goal, Bill } from './types';
import { subDays, subMonths, format, addDays } from 'date-fns';

const today = new Date();
const fmt = (d: Date) => format(d, 'yyyy-MM-dd');

export const seedAccounts: Account[] = [
  {
    id: 'acc-1',
    name: 'Chase Checking',
    type: 'checking',
    balance: 8420.55,
    currency: 'USD',
    color: '#3b82f6',
    icon: '🏦',
    createdAt: fmt(subMonths(today, 12)),
  },
  {
    id: 'acc-2',
    name: 'High-Yield Savings',
    type: 'savings',
    balance: 24150.00,
    currency: 'USD',
    color: '#22c55e',
    icon: '💰',
    createdAt: fmt(subMonths(today, 12)),
  },
  {
    id: 'acc-3',
    name: 'Visa Platinum',
    type: 'credit',
    balance: -1840.20,
    currency: 'USD',
    color: '#ec4899',
    icon: '💳',
    creditLimit: 10000,
    createdAt: fmt(subMonths(today, 8)),
  },
  {
    id: 'acc-4',
    name: 'Investment Portfolio',
    type: 'investment',
    balance: 45200.00,
    currency: 'USD',
    color: '#8b5cf6',
    icon: '📈',
    createdAt: fmt(subMonths(today, 24)),
  },
  {
    id: 'acc-5',
    name: 'Cash Wallet',
    type: 'cash',
    balance: 320.00,
    currency: 'USD',
    color: '#f59e0b',
    icon: '👛',
    createdAt: fmt(subMonths(today, 6)),
  },
];

function makeTransaction(
  id: string,
  accountId: string,
  type: 'income' | 'expense' | 'transfer',
  amount: number,
  category: string,
  description: string,
  daysAgo: number,
  tags: string[] = [],
  toAccountId?: string,
): Transaction {
  return {
    id,
    accountId,
    type,
    amount,
    category,
    description,
    date: fmt(subDays(today, daysAgo)),
    tags,
    toAccountId,
  };
}

export const seedTransactions: Transaction[] = [
  // Income
  makeTransaction('t-1', 'acc-1', 'income', 5500, 'Salary', 'Monthly Salary - Tech Corp', 0, ['work']),
  makeTransaction('t-2', 'acc-1', 'income', 5500, 'Salary', 'Monthly Salary - Tech Corp', 31, ['work']),
  makeTransaction('t-3', 'acc-1', 'income', 5500, 'Salary', 'Monthly Salary - Tech Corp', 62, ['work']),
  makeTransaction('t-4', 'acc-1', 'income', 5500, 'Salary', 'Monthly Salary - Tech Corp', 93, ['work']),
  makeTransaction('t-5', 'acc-1', 'income', 5500, 'Salary', 'Monthly Salary - Tech Corp', 124, ['work']),
  makeTransaction('t-6', 'acc-2', 'income', 850, 'Investments', 'Dividend Payment', 5, ['passive']),
  makeTransaction('t-7', 'acc-1', 'income', 1200, 'Freelance', 'Web Design Project', 14, ['freelance']),
  makeTransaction('t-8', 'acc-1', 'income', 500, 'Bonus', 'Performance Bonus Q4', 20, ['work']),

  // Housing
  makeTransaction('t-10', 'acc-1', 'expense', 1800, 'Housing', 'Rent - December', 1, ['home']),
  makeTransaction('t-11', 'acc-1', 'expense', 1800, 'Housing', 'Rent - November', 32, ['home']),
  makeTransaction('t-12', 'acc-1', 'expense', 1800, 'Housing', 'Rent - October', 63, ['home']),
  makeTransaction('t-13', 'acc-3', 'expense', 89, 'Utilities', 'Electric Bill', 3, ['bills']),
  makeTransaction('t-14', 'acc-3', 'expense', 45, 'Utilities', 'Internet Service', 3, ['bills']),
  makeTransaction('t-15', 'acc-3', 'expense', 32, 'Utilities', 'Water Bill', 7, ['bills']),

  // Food
  makeTransaction('t-20', 'acc-3', 'expense', 82.40, 'Food & Dining', 'Whole Foods', 1, ['groceries']),
  makeTransaction('t-21', 'acc-3', 'expense', 45.20, 'Food & Dining', 'Chipotle Dinner', 2, ['restaurant']),
  makeTransaction('t-22', 'acc-3', 'expense', 124.60, 'Food & Dining', 'Trader Joe\'s', 5, ['groceries']),
  makeTransaction('t-23', 'acc-5', 'expense', 18.50, 'Food & Dining', 'Coffee Shop', 6, ['coffee']),
  makeTransaction('t-24', 'acc-3', 'expense', 67.30, 'Food & Dining', 'Sushi Restaurant', 8, ['restaurant']),
  makeTransaction('t-25', 'acc-3', 'expense', 95.10, 'Food & Dining', 'Weekly Groceries', 12, ['groceries']),
  makeTransaction('t-26', 'acc-3', 'expense', 38.70, 'Food & Dining', 'Italian Restaurant', 15, ['restaurant']),
  makeTransaction('t-27', 'acc-5', 'expense', 12.00, 'Food & Dining', 'Lunch', 16, ['lunch']),

  // Transportation
  makeTransaction('t-30', 'acc-3', 'expense', 65.00, 'Transportation', 'Gas Station', 2, ['car']),
  makeTransaction('t-31', 'acc-3', 'expense', 65.00, 'Transportation', 'Gas Station', 16, ['car']),
  makeTransaction('t-32', 'acc-3', 'expense', 42.00, 'Transportation', 'Uber Rides', 4, ['rideshare']),
  makeTransaction('t-33', 'acc-3', 'expense', 180.00, 'Transportation', 'Car Insurance', 10, ['insurance']),

  // Shopping
  makeTransaction('t-40', 'acc-3', 'expense', 156.80, 'Shopping', 'Amazon - Electronics', 3, ['online']),
  makeTransaction('t-41', 'acc-3', 'expense', 89.99, 'Shopping', 'Nike Shoes', 9, ['clothing']),
  makeTransaction('t-42', 'acc-3', 'expense', 45.00, 'Shopping', 'Target', 11, ['household']),
  makeTransaction('t-43', 'acc-3', 'expense', 220.00, 'Shopping', 'Winter Jacket', 18, ['clothing']),

  // Entertainment
  makeTransaction('t-50', 'acc-3', 'expense', 15.99, 'Subscriptions', 'Netflix', 1, ['streaming']),
  makeTransaction('t-51', 'acc-3', 'expense', 13.99, 'Subscriptions', 'Spotify', 1, ['music']),
  makeTransaction('t-52', 'acc-3', 'expense', 9.99, 'Subscriptions', 'Hulu', 1, ['streaming']),
  makeTransaction('t-53', 'acc-3', 'expense', 65.00, 'Entertainment', 'Concert Tickets', 6, ['events']),
  makeTransaction('t-54', 'acc-3', 'expense', 28.00, 'Entertainment', 'Movie Night', 13, ['movies']),

  // Health
  makeTransaction('t-60', 'acc-3', 'expense', 35.00, 'Health', 'Gym Membership', 1, ['fitness']),
  makeTransaction('t-61', 'acc-3', 'expense', 120.00, 'Health', 'Doctor Visit', 8, ['medical']),
  makeTransaction('t-62', 'acc-3', 'expense', 48.50, 'Health', 'Pharmacy', 11, ['medical']),

  // Travel
  makeTransaction('t-70', 'acc-3', 'expense', 420.00, 'Travel', 'Flight to NYC', 25, ['travel']),
  makeTransaction('t-71', 'acc-3', 'expense', 280.00, 'Travel', 'Hotel - NYC', 25, ['travel']),

  // Education
  makeTransaction('t-80', 'acc-1', 'expense', 99.00, 'Education', 'Udemy Course Bundle', 20, ['learning']),

  // Transfers
  makeTransaction('t-90', 'acc-1', 'transfer', 1000, 'Transfer', 'To Savings', 5, [], 'acc-2'),
  makeTransaction('t-91', 'acc-1', 'transfer', 500, 'Transfer', 'Credit Card Payment', 3, [], 'acc-3'),
  makeTransaction('t-92', 'acc-1', 'transfer', 1000, 'Transfer', 'To Savings', 35, [], 'acc-2'),

  // More older transactions
  makeTransaction('t-100', 'acc-3', 'expense', 72.30, 'Food & Dining', 'BBQ Restaurant', 35, ['restaurant']),
  makeTransaction('t-101', 'acc-3', 'expense', 108.90, 'Food & Dining', 'Monthly Groceries', 38, ['groceries']),
  makeTransaction('t-102', 'acc-3', 'expense', 55.00, 'Transportation', 'Gas Station', 40, ['car']),
  makeTransaction('t-103', 'acc-3', 'expense', 199.00, 'Shopping', 'AirPods', 42, ['electronics']),
  makeTransaction('t-104', 'acc-1', 'income', 800, 'Freelance', 'Logo Design', 45, ['freelance']),
  makeTransaction('t-105', 'acc-3', 'expense', 340.00, 'Health', 'Dental Cleaning', 50, ['dental']),
  makeTransaction('t-106', 'acc-3', 'expense', 88.00, 'Food & Dining', 'Grocery Run', 55, ['groceries']),
  makeTransaction('t-107', 'acc-3', 'expense', 62.00, 'Entertainment', 'Bowling Night', 60, ['fun']),
  makeTransaction('t-108', 'acc-3', 'expense', 48.00, 'Transportation', 'Uber Pool', 65, ['rideshare']),
  makeTransaction('t-109', 'acc-3', 'expense', 290.00, 'Shopping', 'Holiday Gifts', 70, ['gifts']),
];

export const seedBudgets: Budget[] = [
  { id: 'b-1', category: 'Food & Dining', amount: 600, period: 'monthly', color: '#f59e0b', icon: '🍔' },
  { id: 'b-2', category: 'Housing', amount: 2000, period: 'monthly', color: '#6366f1', icon: '🏠' },
  { id: 'b-3', category: 'Transportation', amount: 350, period: 'monthly', color: '#10b981', icon: '🚗' },
  { id: 'b-4', category: 'Shopping', amount: 300, period: 'monthly', color: '#ec4899', icon: '🛍️' },
  { id: 'b-5', category: 'Entertainment', amount: 150, period: 'monthly', color: '#8b5cf6', icon: '🎬' },
  { id: 'b-6', category: 'Health', amount: 200, period: 'monthly', color: '#ef4444', icon: '⚕️' },
  { id: 'b-7', category: 'Subscriptions', amount: 80, period: 'monthly', color: '#a855f7', icon: '📱' },
  { id: 'b-8', category: 'Travel', amount: 500, period: 'monthly', color: '#06b6d4', icon: '✈️' },
];

export const seedGoals: Goal[] = [
  {
    id: 'g-1',
    name: 'Emergency Fund',
    description: '6 months of living expenses',
    targetAmount: 30000,
    currentAmount: 24150,
    deadline: fmt(addDays(today, 120)),
    category: 'emergency',
    color: '#ef4444',
    icon: '🛡️',
    isCompleted: false,
    createdAt: fmt(subMonths(today, 6)),
  },
  {
    id: 'g-2',
    name: 'Hawaii Vacation',
    description: 'Family trip to Maui',
    targetAmount: 5000,
    currentAmount: 2800,
    deadline: fmt(addDays(today, 180)),
    category: 'vacation',
    color: '#06b6d4',
    icon: '🏖️',
    isCompleted: false,
    createdAt: fmt(subMonths(today, 3)),
  },
  {
    id: 'g-3',
    name: 'New MacBook Pro',
    description: 'M4 Max upgrade for work',
    targetAmount: 3500,
    currentAmount: 3500,
    deadline: fmt(subDays(today, 5)),
    category: 'purchase',
    color: '#8b5cf6',
    icon: '💻',
    isCompleted: true,
    createdAt: fmt(subMonths(today, 4)),
  },
  {
    id: 'g-4',
    name: 'Retirement Fund',
    description: '401k supplement',
    targetAmount: 100000,
    currentAmount: 45200,
    deadline: fmt(addDays(today, 3650)),
    category: 'retirement',
    color: '#22c55e',
    icon: '🏖️',
    isCompleted: false,
    createdAt: fmt(subMonths(today, 24)),
  },
  {
    id: 'g-5',
    name: 'House Down Payment',
    description: '20% down on a $600k home',
    targetAmount: 120000,
    currentAmount: 28000,
    deadline: fmt(addDays(today, 730)),
    category: 'home',
    color: '#f59e0b',
    icon: '🏡',
    isCompleted: false,
    createdAt: fmt(subMonths(today, 12)),
  },
];

export const seedBills: Bill[] = [
  {
    id: 'bill-1',
    name: 'Rent',
    amount: 1800,
    frequency: 'monthly',
    dueDay: 1,
    category: 'Housing',
    color: '#6366f1',
    icon: '🏠',
    isAutoPay: false,
    nextDueDate: fmt(addDays(today, 5)),
    lastPaidDate: fmt(subDays(today, 26)),
    payments: [
      { date: fmt(subDays(today, 26)), amount: 1800 },
      { date: fmt(subDays(today, 57)), amount: 1800 },
    ],
  },
  {
    id: 'bill-2',
    name: 'Electric Bill',
    amount: 89,
    frequency: 'monthly',
    dueDay: 15,
    category: 'Utilities',
    color: '#f59e0b',
    icon: '💡',
    isAutoPay: true,
    nextDueDate: fmt(addDays(today, 8)),
    lastPaidDate: fmt(subDays(today, 23)),
    payments: [{ date: fmt(subDays(today, 23)), amount: 89 }],
  },
  {
    id: 'bill-3',
    name: 'Netflix',
    amount: 15.99,
    frequency: 'monthly',
    dueDay: 12,
    category: 'Subscriptions',
    color: '#ef4444',
    icon: '📺',
    isAutoPay: true,
    nextDueDate: fmt(addDays(today, 11)),
    lastPaidDate: fmt(subDays(today, 20)),
    payments: [{ date: fmt(subDays(today, 20)), amount: 15.99 }],
  },
  {
    id: 'bill-4',
    name: 'Spotify',
    amount: 13.99,
    frequency: 'monthly',
    dueDay: 18,
    category: 'Subscriptions',
    color: '#22c55e',
    icon: '🎵',
    isAutoPay: true,
    nextDueDate: fmt(addDays(today, 3)),
    lastPaidDate: fmt(subDays(today, 28)),
    payments: [{ date: fmt(subDays(today, 28)), amount: 13.99 }],
  },
  {
    id: 'bill-5',
    name: 'Car Insurance',
    amount: 180,
    frequency: 'monthly',
    dueDay: 10,
    category: 'Insurance',
    color: '#3b82f6',
    icon: '🚗',
    isAutoPay: false,
    nextDueDate: fmt(addDays(today, 2)),
    lastPaidDate: fmt(subDays(today, 29)),
    payments: [{ date: fmt(subDays(today, 29)), amount: 180 }],
  },
  {
    id: 'bill-6',
    name: 'Gym Membership',
    amount: 35,
    frequency: 'monthly',
    dueDay: 5,
    category: 'Health',
    color: '#10b981',
    icon: '💪',
    isAutoPay: true,
    nextDueDate: fmt(addDays(today, 15)),
    lastPaidDate: fmt(subDays(today, 16)),
    payments: [{ date: fmt(subDays(today, 16)), amount: 35 }],
  },
  {
    id: 'bill-7',
    name: 'Internet',
    amount: 45,
    frequency: 'monthly',
    dueDay: 20,
    category: 'Utilities',
    color: '#8b5cf6',
    icon: '📡',
    isAutoPay: true,
    nextDueDate: fmt(addDays(today, 6)),
    lastPaidDate: fmt(subDays(today, 25)),
    payments: [{ date: fmt(subDays(today, 25)), amount: 45 }],
  },
  {
    id: 'bill-8',
    name: 'Health Insurance',
    amount: 320,
    frequency: 'monthly',
    dueDay: 1,
    category: 'Insurance',
    color: '#ec4899',
    icon: '⚕️',
    isAutoPay: true,
    nextDueDate: fmt(addDays(today, 5)),
    lastPaidDate: fmt(subDays(today, 26)),
    payments: [{ date: fmt(subDays(today, 26)), amount: 320 }],
  },
];
